---

- name: Ensure apt cache is up to date
  apt: update_cache=yes
  sudo: yes

- name: Ensure packages are installed
  apt: name={{item}}
  sudo: yes
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2

- name: Write postgres.conf settings
  template: >
    src=postgresql.conf.j2
    dest=/etc/postgresql/9.3/main/postgresql.conf
  sudo: yes
  notify:
    - Restart PostgreSQL

- name: Write pg_hba.conf settings
  template: >
    src=pg_hba.conf.j2
    dest=/etc/postgresql/9.3/main/pg_hba.conf
  sudo: yes
  notify:
    - Restart PostgreSQL

- name: Setup a password for user postgres
  postgresql_user: >
    name=postgres
    password={{postgres_role_password}}
  sudo_user: postgres
  sudo: yes
