---

- name: Generate teams - add job to crontab
  cron: >
    name="Generate teams"
    minute="5"
    hour="18"
    day="2"
    job="{{virtualenv_dir}}/bin/python {{project_root}}/manage.py generate_teams -s >> {{log_dir}}/team_generator.log 2>&1"
  notify:
   - Restart Crontab