language: python
python:
  - 2.7
env: SECRET_KEY='secret_key' MEETUP_API_KEY='secret' DJANGO_SETTINGS_MODULE='meetup_basket.settings.ci'
services:
  - postgresql
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c 'CREATE DATABASE meetupbasket;' -U postgres
script:
  - python manage.py migrate
  - python manage.py test
  - coverage run --source="." manage.py test meetup_integration web
after_success: coveralls
