---

- name: Deploy code
  hosts: all
  remote_user: ubuntu
  roles:
    - deploy
  tags:
    - deploy

- name: Setup PostgreSQL backup
  hosts: all
  remote_user: ubuntu
  roles:
    - db_backup
  tags:
    - db_backup