---

- name: Setub PostgreSQL
  hosts: all
  roles:
    - db
  tags:
    - db

- name: Setup web environment
  hosts: all
  roles:
    - web
  tags:
    - web

- name: Deploy code
  hosts: all
  roles:
    - deploy
  tags:
    - deploy

- name: Setup PostgreSQL backup
  hosts: all
  roles:
    - db_backup
  tags:
    - db_backup